### PR TITLE
Add student report generation

### PR DESCRIPTION
**Pull request by necrobuffalo**
Not much to look at here yet, but thought I'd get some basic PDF creation code up.

### CODE REVIEW

**Comment by necrobuffalo** [comment]
This should be mostly reviewable now, but doesn't take advantage of CAS just yet and will need updating for the table changes for 360 reviews.

**Comment by necrobuffalo** [comment]
Three routes added:
/reportList/<team_id> to list available reports for a given team (check /reportList/0 and click through links to test)
/studentReport/ for the anonymized printable version
/professorReport/ for a deanonymized report

The reports are all in HTML, but will insert page breaks automatically when printed in Firefox (needs testing in Chrome.)

**Review by pdx-cs-lbryan — CHANGES_REQUESTED** [review]
Looks like this is behind Jacob's database update, could you catch this branch up to master and make sure that your usage of the database matches his changes?

**Comment by necrobuffalo** [comment]
Incorporated Jacob's changes and put some of the sample data back in.

**Review by pdx-cs-lbryan — CHANGES_REQUESTED** [review]
This checklist is adapted from the Coding Standards document:

Required Changes Noted in Bold

Is your task complete?
-generates reports

Is the branch caught up to master/ are there merge conflicts still to be resolved?
Branch is ahead of master

Are old files unnecessarily introduced?
Does not look to be the case

Is old code unnecessarily overwritten?
No

Are new issues introduced to existing code? Do existing automated tests continue to work?
**Report Generation: Issue encountered (see below)**
Will check the below features below when fixed
Log In:
Dashboard:
Edit:
Review: 

Has flake8 been checked?
**Changes that should be made based on flake8 output:**

report.py:
report.py:14:28: E231 missing whitespace after ','
report.py:15:25: E231 missing whitespace after ','
report.py:37:1: E302 expected 2 blank lines, found 1
report.py:90:10: E231 missing whitespace after ','
report.py:99:16: E231 missing whitespace after ','
report.py:100:35: E231 missing whitespace after ','
report.py:123:13: E128 continuation line under-indented for visual indent
report.py:124:13: E128 continuation line under-indented for visual indent
report.py:125:13: E128 continuation line under-indented for visual indent
report.py:126:13: E128 continuation line under-indented for visual indent
report.py:127:13: E128 continuation line under-indented for visual indent

app.py:
app.py:79:17: E128 continuation line under-indented for visual indent
app.py:80:17: E128 continuation line under-indented for visual indent
app.py:83:17: E128 continuation line under-indented for visual indent
app.py:84:17: E128 continuation line under-indented for visual indent
app.py:87:17: E128 continuation line under-indented for visual indent
app.py:88:17: E128 continuation line under-indented for visual indent

gbmodel/model_sqlalchemy.py:
gbmodel/model_sqlalchemy.py:193:23: E703 statement ends with a semicolon


uses 4 spaces where appropriate, not tabs?
yes

camelCase for class names, snake_case for variable and function names?
yes

code is commented?
**classes/functions could use comments stating their purpose/usage**

Does the code handle edge cases? Are try/except statements used sufficiently?
**Needs try/except statements when working with the database, other error handling would be good**
perhaps would fix this:
Bug encountered: 
    File "/home/bryan/Documents/merging/adam/capstone360/report.py", line 33, in get

    pdf = _make_student_report_pdf(student_id, session_id, is_final, is_professor_report=True)

    File "/home/bryan/Documents/merging/adam/capstone360/report.py", line 72, in _make_student_report_pdf

    name = student.name

    AttributeError: 'NoneType' object has no attribute 'name'

Is there documentation on how to test your code somewhere?
I don't see any, would be nice to have

**Comment by necrobuffalo** [comment]
Fleshed out the docstrings a bit more and added some error checking. Not sure where we're putting UI testing instructions for now, but:

/reportList/0 should render a list of students on Team 0/Session 0.
/reportList/1999 should display empty lists, and say there's no students found for that team.
From /reportList/0:
* clicking a student name should make a report with names attached to comments. Changing the parameters in the URL to a nonexistent student should cause a 404.
* clicking the button at the bottom of the card should produce anonymous reports for all team members. As with individual reports, changing to a nonexistent team_id should 404.

**Review by pdx-cs-lbryan — CHANGES_REQUESTED** [review]
please make sure that the branch is ahead of master

**Comment by necrobuffalo** [comment]
Fixed, also here's a SQL blob with the old test data (not loading it myself to avoid merge conflicts with binaries):
```
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.535073',0,0,0,0,1,2,3,4,5,4,3,2,1,2,0,'ehehe','grggr','ergg','ethheth',NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.540400',0,0,0,6,2,2,2,2,2,2,2,NULL,NULL,NULL,0,'eheth','rgerg','gwegwe',NULL,NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.543028',0,0,0,12,3,3,3,3,3,3,3,NULL,NULL,NULL,0,'ethte','gwrgre','gwegw',NULL,NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.550765',0,0,0,18,4,4,4,4,4,4,4,NULL,NULL,NULL,0,'hrhed','ewf','efew',NULL,NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.556732',0,0,0,24,5,5,5,5,5,5,5,NULL,NULL,NULL,0,'rheherh','ewgw','rgrwgw',NULL,NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.568274',0,0,0,30,4,3,4,3,4,3,4,NULL,NULL,NULL,0,'erher','herher','rgr',NULL,NULL,0);
INSERT INTO "reports" VALUES('2019-04-17 22:11:17.570883',0,0,0,36,1,2,1,2,1,2,1,NULL,NULL,NULL,100,'thth','rgerg','egweg',NULL,NULL,0);
```

**Comment by pdx-cs-lbryan** [comment]
* Report generation should include things like the learned category
* Please take the time to add some additional comments on class/method purposes
* some code in report.py could use additional error handling (particularly around database calls)

**Review by pdx-cs-lbryan — APPROVED** [review]

**Pull request merged**
