### PR TITLE
Working add & remove with Sqlite

### PR DESCRIPTION
**Pull request by anguye2**

### CODE REVIEW

**Comment by J8cob1** [comment]
So I am having some trouble getting flask to run on this branch

**Review by pdx-cs-lbryan — CHANGES_REQUESTED** [review]
port needs to be an integer in app.py

I think Jacob wants the psu logo removed

When I tried to remove a student I got the following error:
sqlite3.IntegrityError: UNIQUE constraint failed: removed_students.id, removed_students.session_id

I got the same error when trying to remove a team.

**Comment by pdx-cs-lbryan** [comment]
This time removing teams worked, removing a student from a team worked. Removing all students from a team gave me the same error as before:
sqlite3.IntegrityError: UNIQUE constraint failed: removed_students.id, removed_students.session_id

**Comment by longn5** [comment]
Closing.

**Pull request closed without merging**
