### PR TITLE
Track points and self-reported scores on reports

### PR DESCRIPTION
**Pull request by necrobuffalo**
After submitting a review, if you view the report for yourself you should see your self-reported scores marked with asterisks. On printable reports, self-reported strengths/weaknesses have also been highlighted. Also added traits to work on to the report template.

What you learned should show up only on professor reports, both midterm and final.
Proud of your accomplishment should show up only on final professor reports.

### CODE REVIEW

**Review by J8cob1 — CHANGES_REQUESTED** [review]
So there was a cookie problem and the review I was working on got lost, but the jist of what would have been in it is that the app behaved as expected as far as I could tell, but report generation didn't when I filled out both midterm and final reviews. I got a "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'" when I tried generating any of them.

These will need to be fixed

**Comment by necrobuffalo** [comment]
@J8cob1 do you have a full traceback for that error? Not a big deal if not but it'll make it much easier to track down.

**Comment by J8cob1** [comment]
Traceback:

```
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
return self.dispatch_request(*args, **kwargs)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
return meth(*args, **kwargs)
File "/home/jcrisan/.local/lib/python3.6/site-packages/flask_cas/__init__.py", line 102, in wrap
return function(*args, **kwargs)
File "/home/jcrisan/Projects/capstone360-2/report.py", line 64, in get
pdf = _make_printable_reports(session_id, is_final)
File "/home/jcrisan/Projects/capstone360-2/report.py", line 90, in _make_printable_reports
report = report + _make_student_report_pdf(s.id, session_id, is_final)
File "/home/jcrisan/Projects/capstone360-2/report.py", line 184, in _make_student_report_pdf
scores[key][this_score-1] = "**{}".format(scores[key][this_score-1])
```

**Comment by necrobuffalo** [comment]
Thanks! Also if you want to format stuff like that more nicely in the future with indentation and such you can wrap it in three backticks, ex:
```
def foo():
    pass
```

**Comment by pdx-cs-lbryan** [comment]
All styling checks and application tests passed, will approve once Jacob tries to replicate the bug he had earlier

**Review by J8cob1 — APPROVED** [review]

**Pull request merged**
