### PR TITLE
Close Reviews

### PR DESCRIPTION
**Pull request by pdx-cs-lbryan**
New Features:
* 'Close Reviews' button on Professor Dashboard
-How to use it:
---Go to Prof Dashboard
---Go to Edit
---Click 'Close Reviews'
-How to Test It:
----Are you able to click it?
----Does it take you to /setAvailable/?

* Student 'active' attribute has a new use as detecting open/closed reviews
-How to use it:
---create new students (mock db won't have the correct initial value)
---use all methods of adding students -- dashboard, csv, student self-adding
-How to test it:
---are the new students given 'open' for active?

* Professor can close/open reviews
-How to use it:
-----As described above, go to /setAvailable/
-----Use the dropdown to select open or closed
-How to test it:
-----Test the following cases. When set to 'closed' ensure no active reviews. When set to 'open' ensure active reviews (be mindful of any mock data which may not have been initialized correctly, you can do an initial set to 'open' to fix this per session)

Review Type, Open/Closed, Reviews should be Available/Not Available, marked as late?
on time midterm - fresh, open, available, no
on time midterm - edit on time, open, available, no
on time midterm - edit late, open, available, no
late midterm - edit late, open, available, yes

Then repeat for final [you should not need to repeat all edge cases for final, just ensure that it works here too]

As a final check, put a student in two different capstone sessions. Allow them to access reviews in one and not the other. Are they blocked from the correct review? If you switch the accessible and inaccessible reviews, are they still blocked from the correct review?

Also test: if you open up the review, then switch reviews to be closed, then try to submit the review, are you able to? (you should get a message saying they are closed)

Bug Fixes:
* Error when there is no matching professor for a capstone session
-How to use it:
----have capstone sessions in the database with an assigned prof id that does not match an existing prof id
-how to test it:
----do those capstones show up? (they shouldn't in this set up, that may be something to change later)
----do you experience any crashes?

*Changed header on set date to 'set date' from 'add team'

***Remember to check all application features!***

### CODE REVIEW

**Review by J8cob1 — COMMENTED** [review]
New Features:
* 'Close Reviews' button on Professor Dashboard
-How to use it:
---Go to Prof Dashboard
---Go to Edit
---Click 'Close Reviews'
-How to Test It:
----Are you able to click it? **- Yes**
----Does it take you to /setAvailable/? **- Yes**

* Student 'active' attribute has a new use as detecting open/closed reviews
-How to use it:
---create new students (mock db won't have the correct initial value)
---use all methods of adding students -- dashboard, csv, student self-adding
-How to test it:
---are the new students given 'open' for active? **- Yes**

* Professor can close/open reviews
-How to use it:
-----As described above, go to /setAvailable/
-----Use the dropdown to select open or closed
-How to test it:
-----Test the following cases. 
--------When set to 'closed' ensure no active reviews. **- Yes**
--------When set to 'open' ensure active reviews (be mindful of any mock data which may not have been initialized correctly, you can do an initial set to 'open' to fix this per session) **- Yes (I created a team with newly students only via from csv import, self-register and manual addition via professor dashboard, and tested with that)**

Review Type, Open/Closed, Reviews should be Available/Not Available, marked as late?
on time midterm - fresh, open, available, no **- Works**
on time midterm - edit on time, open, available, no **- Works
on time midterm - edit late, open, available, no **- Seems to work as described**
late midterm - edit late, open, available, yes **- Works**


Then repeat for final [you should not need to repeat all edge cases for final, just ensure that it works here too] **- it looks good**

As a final check, put a student in two different capstone sessions. Allow them to access reviews in one and not the other. Are they blocked from the correct review? If you switch the accessible and inaccessible reviews, are they still blocked from the correct review? **- Yes**

Also test: if you open up the review, then switch reviews to be closed, then try to submit the review, are you able to? (you should get a message saying they are closed) **- Yes. I get a message saying there you have no open reviews (not necessarily that "reviews are closed" verbatim. There is an "Error when identifiyng user" message in the console as well)**

Bug Fixes:
* Error when there is no matching professor for a capstone session
-How to use it:
----have capstone sessions in the database with an assigned prof id that does not match an existing prof id
-how to test it:
----do those capstones show up? (they shouldn't in this set up, that may be something to change later) **no**
----do you experience any crashes? **no**

*Changed header on set date to 'set date' from 'add team' **not sure we if we could see it anyway**

--------------------------The Following Was Tested After Updating From Master------------------------------------

Features: loosely checked
- Login: **Seems to work**
  - Student: **Seems to work**
  - Professor: **Seems to work**
- Student Dashboard: **Seems to work**
- Prof Dashboard:
  - Add Student: **Seems to work**
  - Import Student: **Works**
  - Add Session: **Seems to work**
  - Remove Session: **Session appeared removed on dashboard** -- see if modified
  - Add Team: **Seems to work**
  - Remove Team: **Seems to work** -- see if modified
  - Assign Student to Team:
  - Remove Student: **need to remove myself twice to make sure it works, but I was able to remove students**
  - Set Dates: **Seemed fine**
  - Set Team Lead: **Seemed to work?**
  - Cancel Button: **Seems to work**
  - Max/Min Points: **Seems to work**
- Register Student: **Still worked (though the open attribute is not set though)**
- View Student: **Seems to work, though there is a formatting problem**
- View Review: **Seems to work**
- Fill out review: **Seemed fine when I tested it**
- Generate Student Reports: **Worked**
- Generate Professor Reports:  **I think this one might be working fine**

I presume the things working before the update continued to work (though we can check again after the proper modifications are made)

**Comment by pdx-cs-lbryan** [comment]
updated and resolved merged conflicts, did some testing to ensure continued functionality

**Review by J8cob1 — CHANGES_REQUESTED** [review]
Overall, it seemed fine, though we may want to set the "active" attribute to "open" in the student self registration process. It is also not caught up to master anymore.

**Comment by J8cob1** [comment]
Now we just need to verify that everything still works

**Review by J8cob1 — DISMISSED** [review]

**Comment by J8cob1** [comment]
Please see the squashed version of this branch and consider merging that one. This one won't work on the VM.

**Pull request closed without merging**
